### ISSUE TITLE
Feedback and use cases for dist

### ISSUE THREAD

**Issue by csoriano1618** [jpakkane/dist#1]
As requested, here is what we currently do with autotools in Nautilus:
- pack the code (included submodules) into a tar with the project version in configure/meson.build
- extract the tar and build
- execute tests
And I think that's it. Our current simple script for packing the code is https://git.gnome.org/browse/nautilus/tree/make_release.sh
for packing submodules there is also https://github.com/meitar/git-archive-all.sh but it's GPL3 and we are GPL2, so we cannot use it.

**Comment by jpakkane** [comment]
Moved [here](https://github.com/mesonbuild/meson/issues/877).
